First models
vlaad01/ws_test_task pull request #2
Opened 2021-11-01 10:20 UTC by vlaad01

2021-11-02 14:58 UTC, isoldatenko requested changes

2021-11-02 14:58 UTC, isoldatenko commented on app/core/abstract_models.py
> +class BaseModel(models.Model):
Лучше дать другое название, например `SoftDelete`

2021-11-02 14:58 UTC, isoldatenko commented on app/core/abstract_models.py
> +    discount_percent = models.PositiveIntegerField(verbose_name='Скидка (%)')
поставь валидация, чтобы минимум был один процент

2021-11-02 14:58 UTC, isoldatenko commented on app/customer/models.py
> +    balance = models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Баланс')
валидация на то, что баланс не может быть меньше нуля

2021-11-02 14:58 UTC, isoldatenko commented on app/customer/models.py
> +    customer.balance -= instance.price
Сигналы лучше выносить в отдельные файлы

2021-11-02 14:58 UTC, isoldatenko commented on app/customer/models.py
> +
одна пустая строка в конце файла

2021-11-02 14:58 UTC, isoldatenko commented on app/customer/models.py
> +
одна пустая строка между импортами

2021-11-02 14:58 UTC, isoldatenko commented on app/customer/models.py
> +    price = models.DecimalField(decimal_places=3, max_digits=10)
валидация на то, что цена не может быть меньше нуля

2021-11-02 14:58 UTC, isoldatenko commented on app/customer/models.py
> +    max_price = models.DecimalField(decimal_places=3, max_digits=10)
валидация на то, что цена не может быть меньше нуля

2021-11-02 14:58 UTC, isoldatenko commented on app/customer/models.py
> +    address = models.CharField(max_length=256, verbose_name='Адрес')
Адрес можно вынести в отдельную модельку, которая будет хранить страну / город / улицу / номер дома

2021-11-02 14:58 UTC, isoldatenko commented on app/showroom/models.py
> +    showroom.save()
сигналы в отдельный файл

2021-11-02 14:58 UTC, isoldatenko commented on app/showroom/models.py
> +    model = models.CharField(max_length=256, verbose_name='Модель')
Отдельно также можно выделить модель производителя -> Manufacturer

2021-11-02 14:58 UTC, isoldatenko commented on app/showroom/models.py
> +    hp = models.PositiveIntegerField(verbose_name='Мощность (л.с.)')
Можно поставить валидация на максимальное значение мощности

2021-11-02 14:58 UTC, isoldatenko commented on app/showroom/models.py
> +    address = models.CharField(max_length=256, verbose_name='Адрес')
Адрес также можно вынести в отдельную модель

2021-11-02 14:58 UTC, isoldatenko commented on app/showroom/models.py
> +        verbose_name_plural = 'Продажи'
А Purchase и sale в контексте клиента и автосалона не одни и те же по своей сути модели?

2021-11-02 14:58 UTC, isoldatenko commented on app/showroom/models.py
> +class Showroom_m2m_Supplier(models.Model):
поле count тоже нужно добавить

2021-11-02 14:58 UTC, isoldatenko commented on app/showroom/models.py
> +    price = models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Цена')
можно на основе двух моделей вынести абстрактную

2021-11-02 14:58 UTC, isoldatenko commented on app/supplier/models.py
> +    address = models.CharField(max_length=256, verbose_name='Адрес')
Также можно вынести модель адрес

2021-11-02 14:58 UTC, isoldatenko commented on app/supplier/models.py
> +    sales_count = models.PositiveIntegerField(verbose_name='Количество сделок')
лишнее поля, могут быть рассчитаны функциями агрегирования используя уже существующие поля

2021-11-02 14:58 UTC, isoldatenko commented on app/supplier/models.py
> +    supplier.save()
вынеси сигналы в отдельный файл

2021-11-03 11:26 UTC, vlaad01 commented on app/showroom/models.py
> +class Showroom_m2m_Supplier(models.Model):
Не совсем понял куда добавить count. Если showroom_m2m_supplier, то я думал хранить только модель машины, которая закупается у поставщика.

2021-11-03 11:27 UTC, vlaad01 commented on app/showroom/models.py
> +    price = models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Цена')
Ну тут продолжение вопроса про count, а то получается что абстрактная модель будет только с одним полем: ссылкой на showroom

2021-11-05 12:42 UTC, isoldatenko commented on app/showroom/models.py
> +class Showroom_m2m_Supplier(models.Model):
да, count не должен тут храниться

2021-11-05 12:43 UTC, isoldatenko commented on app/showroom/models.py
> +    price = models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Цена')
в абстрактную модель можно вынести car и price

2021-11-05 12:49 UTC, isoldatenko requested changes

2021-11-05 12:49 UTC, isoldatenko commented on app/customer/signals.py
> +    customer.balance -= instance.price
используй F выражение

2021-11-05 12:49 UTC, isoldatenko commented on app/showroom/signals.py
> +    showroom.balance += showroom_car.price
тут тоже F выражение

2021-11-05 12:49 UTC, isoldatenko commented on app/supplier/models.py
> +    address = models.OneToOneField(Address, on_delete=models.CASCADE)
models.SET_NULL используй тут лучше, чтобы при удалении адреса поставщик не удалялся

2021-11-05 12:49 UTC, isoldatenko commented on app/supplier/models.py
> +    address = models.OneToOneField(Address, on_delete=models.CASCADE)
касается всех моделей связанных

2021-11-05 12:49 UTC, isoldatenko commented on app/showroom/models.py
> +class Discount(AbstractDiscount):
Две модельки с именем Discount, поменяй название слегка

2021-11-05 12:49 UTC, isoldatenko commented on app/showroom/models.py
> +        related_name='purchase_history'
добавь еще related_query_name, должно быть в единственном числе

2021-11-10 14:04 UTC, isoldatenko approved these changes

2021-11-10 14:43 UTC, merged