API v1
vlaad01/ws_test_task pull request #3
Opened 2021-11-11 14:09 UTC by vlaad01

2021-11-12 12:39 UTC, isoldatenko requested changes

2021-11-12 12:39 UTC, isoldatenko commented on app/config/urls.py
> +)
Добавь переменную `USE_SWAGGER`, чтобы определять, когда нужно подключать сваггер, а когда нет

2021-11-12 12:39 UTC, isoldatenko commented on app/customer/admin.py
> +admin.site.register(Offer)
Закастомь админку, регистрируя модельки классом

2021-11-12 12:39 UTC, isoldatenko commented on app/customer/serializers.py
> +        fields = ['first_name', 'last_name', 'email', 'balance', 'address']
используй tuple здесь

2021-11-12 12:39 UTC, isoldatenko commented on app/config/urls.py
> +    path('', include('supplier.urls')),
нужно еще Django debug toolbar подключить

2021-11-12 12:39 UTC, isoldatenko commented on app/customer/serializers.py
> +        exclude = ('is_active', )
объявил поле customer, но не используешь его

2021-11-12 12:39 UTC, isoldatenko commented on app/customer/views.py
> +            url_path='(?P<pk>[^/.]+)/purchase_history')
достаточно написать detail=True и не указывать url

2021-11-12 12:39 UTC, isoldatenko commented on app/customer/views.py
> +        customer = get_object_or_404(Customer, id=pk)
используй метод self.get_object(), который определен на уровне view set

2021-11-12 12:39 UTC, isoldatenko commented on app/customer/views.py
> +        return Response(OfferSerializer(customer.offers, many=True).data)
возвращай статус вместе с Response

2021-11-12 12:39 UTC, isoldatenko commented on app/showroom/admin.py
> +from .models import *
не используй `*` в импортах

2021-11-12 12:39 UTC, isoldatenko commented on app/showroom/serializers.py
> +from .models import Showroom, Car, Address, Manufacturer, Sale, Discount, Showroom_m2m_Car
используй абсолютные импорты

2021-11-12 12:39 UTC, isoldatenko commented on app/showroom/views.py
> +        if serializer.is_valid():
используй `serializer.is_valid(raise_exception=True)`

2021-11-12 12:39 UTC, isoldatenko commented on app/supplier/views.py
> +            methods=['get'],
используй tuple

2021-11-12 12:39 UTC, isoldatenko commented on app/supplier/views.py
> +            methods=['get'],
Пиши названия методов в большом регистре - GET

2021-11-15 11:20 UTC, vlaad01 commented on app/customer/serializers.py
> +        exclude = ('is_active', )
Там в meta exclude, а не fields. Вроде все норм работает

2021-11-17 14:30 UTC, isoldatenko requested changes

2021-11-17 14:30 UTC, isoldatenko commented on app/config/settings.py
> +
Раздели INSTALLED_APPS на DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS соответственно

2021-11-17 14:30 UTC, isoldatenko commented on app/customer/views.py
> +        if serializer.is_valid(raise_exception=True):
Когда используешь raise_exception то можно не проверять через if, что данные валидные, он сам вернет респонс с статус кодом 400 и текстом ошибки, если произойдет какая - то ошибка валидация

2021-11-17 14:30 UTC, isoldatenko commented on app/showroom/serializers.py
> +        fields = ['country', 'city', 'street', 'building']
тут тоже tuple юзай

2021-11-18 12:29 UTC, isoldatenko approved these changes

2021-11-18 12:48 UTC, merged