Added celery tasks
vlaad01/ws_test_task pull request #7
Opened 2021-12-02 10:20 UTC by vlaad01

2021-12-05 09:23 UTC, isoldatenko requested changes

2021-12-05 09:23 UTC, isoldatenko commented on app/customer/services.py
> +        if self.max_price > self.customer.balance:
Нужно также учитывать офферы, которые уже были созданы юзером, но еще не выполнились

2021-12-05 09:23 UTC, isoldatenko commented on app/customer/services.py
> +        from customer.tasks import car_search_task
в данном случае лучше вынеси в глобальные импорты

2021-12-05 09:23 UTC, isoldatenko commented on app/customer/tasks.py
> +    if car is not None and offer.max_price >= car.final_price:
достаточно будет `if car and offer.max_price >= car.final_price`

2021-12-05 09:23 UTC, isoldatenko commented on app/showroom/tasks.py
> +        if discount is not None:
`if discount` будет достаточно

2021-12-05 09:23 UTC, isoldatenko commented on app/showroom/tasks.py
> +        if supplier_car is not None:
`if supplier_car`

2021-12-08 19:10 UTC, vlaad01 commented on app/customer/services.py
> +        from customer.tasks import car_search_task
Там трабл с циклическим импортом, а разделять сервисы не очень хочется

2021-12-14 18:08 UTC, isoldatenko approved these changes

2021-12-15 18:58 UTC, merged